name: "Hello World workflow"

on:
  push:
    branches:
        - master

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: "Prints Hello World!"
        run: echo "Hello World!!"
      - name: "Prints This is just another addition!"
        run: echo "This is just another addition V1!!"
      - name: "Prints current date"
        run: date
