name: "Hello World workflow"

on:
  push:
    branches:
        - master
        - test
  pull_request:
    branches:
        - master
    types:
        - closed    
  workflow_dispatch:

jobs:
  on-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: "Prints Hello World!"
        run: echo "Hello World!!"
      - name: "Prints This is just another addition!"
        run: echo "This is a push request!!"
      - name: "Prints current date"
        run: date
  on-pull-request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: "Prints Hello World!"
        run: echo "Hello World!!"
      - name: "Prints This is just another addition!"
        run: echo "This is a pll request!!"
      - name: "Prints current date"
        run: date
  on-pull-request-closed:
    runs-on: ubuntu-latest
    steps:
       - name: "Running on pull request closed"
         run: echo "Running on pull reuqest closed"
  on-workflow-dispatch:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: "Prints Hello World!"
        run: echo "Hello World!!"
      - name: "Prints This is just another addition!"
        run: echo "This is Workflow Dispatch!!"
      - name: "Prints current date"
        run: date